name: ci
on:
    pull_request: ~
    push:
        branches:
            - master

env:
    GITHUB_TOKEN: ${{ github.token }}

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                install-args: ['', lowest]
            fail-fast: false
        steps:
            - name: cancel
              uses: styfle/cancel-workflow-action@0.11.0

            - name: checkout
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@2.24.0
              with:
                  php-version: '8.1'
                  extensions: apcu, redis
                  dependency-versions: "${{ matrix.dependencies }}"
                  coverage: none

            - name: composer
              uses: ramsey/composer-install@2.2.0
              with:
                  composer-options: "--prefer-dist --classmap-authoritative"

            - name: phpspec
              run: |
                  vendor/bin/phpspec run

            - name: phpstan-cache
              uses: actions/cache@v3.2.4
              with:
                  key: phpstan-${{ github.ref }}-${{ github.sha }}
                  path: .phpstan-cache
                  restore-keys: |
                      phpstan-${{ github.ref }}-
                      phpstan-

            - name: phpstan
              run: |
                  vendor/bin/phpstan analyze -c ./phpstan.neon
                  vendor/bin/phpstan analyze -c ./phpstan.test.neon

            - name: phpunit
              run: |
                  vendor/bin/phpunit
