name: ci
on:
    pull_request: ~
    push:
        branches:
            - master

env:
    GITHUB_TOKEN: ${{ github.token }}

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '8.1', '8.2', '8.3' ]
                symfony: [ '5.4', '6.4', '7.1' ]
                install-args: ['', '--prefer-lowest --prefer-stable']
            fail-fast: false
        steps:
            - name: cancel
              uses: styfle/cancel-workflow-action@0.9.1

            - name: checkout
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@2.19.0
              with:
                  php-version: ${{ matrix.php }}
                  extensions: apcu, redis

            - name: Composer update on PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
              if: ${{ !cancelled() }}
              run: |
                  composer require --no-update symfony/flex
                  composer config --no-plugins allow-plugins.symfony/flex true
                  SYMFONY_REQUIRE=${{ matrix.symfony }} composer update --classmap-authoritative ${{ matrix.install-args }}

            - name: phpspec
              if: ${{ !cancelled() }}
              run: |
                  vendor/bin/phpspec run

            - name: phpstan
              if: ${{ !cancelled() }}
              run: |
                  vendor/bin/phpstan analyze -c ./phpstan.neon
                  vendor/bin/phpstan analyze -c ./phpstan.test.neon

            - name: phpunit
              if: ${{ !cancelled() }}
              run: |
                  vendor/bin/phpunit
